### ISSUE TITLE
Omit the leading decimal point?

### ISSUE THREAD

**Issue by lambda-fairy** [qntm/minify-numeric-literal#1]
`.98` is also a valid JavaScript number literal—it's equivalent to `0.98`.

**Comment by ferno** [comment]
`minify-numeric-literal` does indeed already do this but you're right about one thing: I forgot to mention it in the README. Will fix. 👍

**Comment by ferno** [comment]
Actually, yeah, the README was just wrong (although `mnl` was right). Whoops.

**Comment by ferno** [comment]
[Fixed](https://github.com/ferno/minify-numeric-literal/commit/ea48423c13b639a6492b546ed35f606af4778dab).
